#
server:
  port: 9080
#
spring:
  application:
    name: EurekaServer
#for actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
#
some-prefix:
  ip: some-ip
  user: some-user
  pswd: some-pswd